### ISSUE TITLE
Docker container timezone is not synced with host

### ISSUE THREAD

**Issue by Kardbord** [TannerKvarfordt/Kard-bot#24]
Containers running the image provided with Kard-bot releases up to at least v1.4.0-beta will not be synchronized to the host's timezone. This is particularly annoying for cron-like functionality such as daily compliments and Wednesday posting.

**Comment by TannerKvarfordt** [comment]
Ideally I would like to set the timezone in docker-compose rather than bake it into the docker image. It might be possible by creating read-only volume mounts for `/etc/timezone`, `/etc/localtime`, and `/usr/share/zoneinfo`. Sounds like there may be some "gotchas" to watch out for due to symlinks. See https://serverfault.com/questions/683605/.
